### ISSUE TITLE
Feature request - a beforeEach stub

### ISSUE THREAD

**Issue by jesseboydgsa** [Madhusuthanan-B/Angular-Testing-Snippets#1]
I think this is a missing feature in your snippets.  
Either have this stub in isolation or created at time of suite creation
 Thanks!

**Comment by Madhusuthanan-B** [comment]
Thanks for the suggestion. I will put this in. Feel free to add and raise a PR

**Comment by Madhusuthanan-B** [comment]
Closing this issue as this is addressed in this: https://github.com/Madhusuthanan-B/Angular-Testing-Snippets/pull/3
